# Generated by Django 3.2.12 on 2022-03-21 15:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
