# Generated by Django 3.2.12 on 2022-03-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_feedback_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='article', to='article.Tags'),
        ),
    ]
